<?xml version="1.0" encoding="utf-8"?><Database Name="CSDL" Class="CauHoiDTO_HTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\CSDL.mdf;Integrated Security=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="CSDLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CauHoi" Member="CauHois">
    <Type Name="CauHoi">
      <Column Name="MaCauHoi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CauHoi" Member="CauHoi1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CauA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CauB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CauC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CauD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CauDung" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="MaKhoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>